In [12]:
import pandas as pd
import numpy as np
import math
from singleLayerNeuralNetwork import SingleLayerNeuralNetwork

AND Operator

In [13]:
data = pd.read_csv("data.csv")

In [14]:
def split_data(data):
    
    y = data['r']
    X = data.drop(labels='r',axis=1)
    
    y_train = y.iloc[:math.floor(data.shape[0]*0.7)]
    X_train = X.iloc[:math.floor(data.shape[0]*0.7)]
    
    X_test = X.iloc[math.floor(data.shape[0]*0.7):]
    y_test = y.iloc[math.floor(data.shape[0]*0.7):]
    
    return X_train,y_train,X_test,y_test

In [15]:
X_train,y_train,X_test,y_test = split_data(data)

def activation_function(s): 
    if s > 1.8:
        return 1
    return 0

In [16]:
model = SingleLayerNeuralNetwork(iterations=100,activation_function=activation_function,weights_interval=[0,1],biais=1,alpha=0.1)

In [17]:
model.fit(X=X_train,y=y_train)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
model.weights

x1    0.4
x2    0.4
x3    0.5
x4    0.0
Name: 3, dtype: float64

In [19]:
model.predict(X_test)

array([0., 1., 0., 0., 1.])

OR Operator

In [28]:
or_data = pd.read_csv("or_data.csv")

In [29]:
X_train_0,y_train_0,X_test_0,y_test_0 = split_data(or_data)

def or_activation_function(s):
    if s >= 1.8:
        return 1
    return 0

In [30]:
model_or = SingleLayerNeuralNetwork(iterations=100,activation_function=or_activation_function,weights_interval=[0,1],biais=1,alpha=0.1)

In [31]:
model_or.fit(X_train_0,y_train_0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
model_or.weights

x1    0.5
x2    0.5
x3    0.7
x4    0.7
Name: 0, dtype: float64

In [33]:
model_or.predict(X_test_0)

array([1., 1., 1., 1., 0.])

Even or Odd

In [34]:
even_odd_data = pd.read_csv("even_odd_data.csv")

In [35]:
X_train_1,y_train_1,X_test_1,y_test_1 = split_data(even_odd_data)

def even_odd_activation_function(s):
    if s >= 1:
        return 1
    return 0

In [36]:
model_even_odd = SingleLayerNeuralNetwork(iterations=100,activation_function=even_odd_activation_function,weights_interval=[0,1],biais=1,alpha=0.1)

In [37]:
model_even_odd.fit(X_train_1,y_train_1)

array([0., 1., 0., 1., 0., 1., 0.])

In [38]:
model_even_odd.weights

x1    6.000000e-01
x2   -1.000000e-01
x3    5.000000e-01
x4   -3.000000e-01
x5   -6.000000e-01
x6   -3.000000e-01
x7    1.387779e-16
Name: 0, dtype: float64

In [39]:
model_even_odd.predict(X_test_1)

array([1., 0., 1.])